# true for novelty search, false for random decisions (true/false)
novelty_search = true

# Initial hunger (valid range 0-10)
hunger = 3

# Initial bravery (valid range 0-10)
bravery = 3 

# The maximum difference between foragers compatibility thresholds (valid range 0-1)
# Higher compat_diff makes the foragers less "fussy" when finding potential mates 
compat_diff = 0.3 # 0 <= x <= 1

# How much to reduce the weight of succesful choice (valid range 0-1)
# this encourages foragers to explore new choices
decay_factor = 0.98

# The effect hunger has on the other attributes. (valid range 0-1)
# A higher hunger combinator makes more drastic changes
hunger_combinator = 0.1

# How much bias is added to choices (valid range 0-1)
positive_multiplier = 0.25 

