# Initial hunger 
hunger = 3 # 0 <= x <= 10
# Initial bravery  
bravery = 3 # 0 <= x <= 10

# The allowed difference between foragers compatibility_threshold 
# Higher compat_diff makes the foragers less "fussy", promoting more diversity
compat_diff = 0.1 # 0 <= x <= 1

# The effect hunger has on the other attributes. 
# A higher hunger combinator makes more drastic changes
hunger_combinator = 0.1 # 0 <= x <= 1
