
hunger = 3.0

bravery = 3.0

# The acceptable difference between two foragers compatibility_thresholds
# A higher compat makes the foragers less "fussy"
# higher compat_diff promotes diversity (if i get round to encoding a smart reproduction method)
compat_diff = 0.1

# The effect hunger has on the other attributes. At intervals, attributes go
# down as the forager gets hungrier. Higher hunger combinators make changes
# more drastic.
hunger_combinator = 0.3
